# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signIn_MainWindow(object):
    def setupUi(self, signIn_MainWindow):
        signIn_MainWindow.setObjectName("signIn_MainWindow")
        signIn_MainWindow.resize(800, 600)
        signIn_MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        signIn_MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        signIn_MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signIn_MainWindow.setWindowIcon(icon)
        signIn_MainWindow.setIconSize(QtCore.QSize(128, 128))
        self.centralwidget = QtWidgets.QWidget(signIn_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(200, 200, 170, 50))
        self.username_label.setMinimumSize(QtCore.QSize(170, 50))
        self.username_label.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setLineWidth(1)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(200, 300, 170, 50))
        self.password_label.setMinimumSize(QtCore.QSize(170, 50))
        self.password_label.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setLineWidth(1)
        self.password_label.setObjectName("password_label")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(400, 310, 200, 40))
        self.password.setMinimumSize(QtCore.QSize(200, 40))
        self.password.setMaximumSize(QtCore.QSize(200, 40))
        self.password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(400, 210, 200, 40))
        self.username.setMinimumSize(QtCore.QSize(200, 40))
        self.username.setMaximumSize(QtCore.QSize(200, 40))
        self.username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username.setObjectName("username")
        self.sure_Button = QtWidgets.QPushButton(self.centralwidget)
        self.sure_Button.setGeometry(QtCore.QRect(590, 475, 200, 50))
        self.sure_Button.setMinimumSize(QtCore.QSize(200, 50))
        self.sure_Button.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/click.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sure_Button.setIcon(icon1)
        self.sure_Button.setIconSize(QtCore.QSize(54, 54))
        self.sure_Button.setObjectName("sure_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setMinimumSize(QtCore.QSize(800, 600))
        self.label.setMaximumSize(QtCore.QSize(800, 600))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.raise_()
        self.username_label.raise_()
        self.password_label.raise_()
        self.password.raise_()
        self.username.raise_()
        self.sure_Button.raise_()
        signIn_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signIn_MainWindow)
        self.statusbar.setObjectName("statusbar")
        signIn_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(signIn_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(signIn_MainWindow)

    def retranslateUi(self, signIn_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        signIn_MainWindow.setWindowTitle(_translate("signIn_MainWindow", "低压断路器故障诊断与在线监测界面"))
        self.username_label.setText(_translate("signIn_MainWindow", "用户名 : "))
        self.password_label.setText(_translate("signIn_MainWindow", "密码 : "))
        self.sure_Button.setText(_translate("signIn_MainWindow", "确定"))
# import signWindow_rc
from MyPlatform import  signWindow_rc