# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signDialog(object):
    def setupUi(self, signDialog):
        signDialog.setObjectName("signDialog")
        signDialog.resize(800, 600)
        signDialog.setMinimumSize(QtCore.QSize(800, 600))
        signDialog.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        signDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signDialog.setWindowIcon(icon)
        signDialog.setAutoFillBackground(False)
        self.username_label = QtWidgets.QLabel(signDialog)
        self.username_label.setGeometry(QtCore.QRect(200, 200, 170, 50))
        self.username_label.setMinimumSize(QtCore.QSize(170, 50))
        self.username_label.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setLineWidth(1)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(signDialog)
        self.password_label.setGeometry(QtCore.QRect(200, 300, 170, 50))
        self.password_label.setMinimumSize(QtCore.QSize(170, 50))
        self.password_label.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setLineWidth(1)
        self.password_label.setObjectName("password_label")
        self.username = QtWidgets.QLineEdit(signDialog)
        self.username.setGeometry(QtCore.QRect(400, 210, 200, 40))
        self.username.setMinimumSize(QtCore.QSize(200, 40))
        self.username.setMaximumSize(QtCore.QSize(200, 40))
        self.username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(signDialog)
        self.password.setGeometry(QtCore.QRect(400, 310, 200, 40))
        self.password.setMinimumSize(QtCore.QSize(200, 40))
        self.password.setMaximumSize(QtCore.QSize(200, 40))
        self.password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password.setObjectName("password")
        self.sure_Button = QtWidgets.QPushButton(signDialog)
        self.sure_Button.setGeometry(QtCore.QRect(590, 475, 200, 50))
        self.sure_Button.setMinimumSize(QtCore.QSize(200, 50))
        self.sure_Button.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/click.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sure_Button.setIcon(icon1)
        self.sure_Button.setIconSize(QtCore.QSize(54, 54))
        self.sure_Button.setObjectName("sure_Button")

        self.retranslateUi(signDialog)
        QtCore.QMetaObject.connectSlotsByName(signDialog)

    def retranslateUi(self, signDialog):
        _translate = QtCore.QCoreApplication.translate
        signDialog.setWindowTitle(_translate("signDialog", "低压断路器故障诊断与在线监测界面"))
        self.username_label.setText(_translate("signDialog", "用户名 : "))
        self.password_label.setText(_translate("signDialog", "密码 : "))
        self.sure_Button.setText(_translate("signDialog", "确定"))
# import signDialog_rc
from MyPlatform import signDialog_rc
