#ifndef TESTCREATESHARELIB_GLOBAL_H
#define TESTCREATESHARELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTCREATESHARELIB_LIBRARY)
#  define TESTCREATESHARELIB_EXPORT Q_DECL_EXPORT
#else
#  define TESTCREATESHARELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTCREATESHARELIB_GLOBAL_H
